name: Translate zh-CN to en-US
on:
  push:
    branches:
      - master # 修改为你的默认分支名称

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install deep-translator

    - name: Translate files
      run: |
        for file in $(find zh-CN -type f -name "*.md"); do
          target_dir="en-US${file#zh-CN}"
          mkdir -p $(dirname "$target_dir")
          python translate.py "$file" "$target_dir"
        done
    - name: list files
      run: ls
    - name: commit 
      run: git add .; git commit -m 'commit translate files'; git push;
