name: Translate zh-CN to en-US
on:
  push:
    branches:
      - master # 修改为你的默认分支名称

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install deep-translator
           pip install mistune

    - name: Translate files
      run: |
        for file in $(find en-US -type f -name "*.md"); do
          target_dir="ja${file#en-US}"
          mkdir -p $(dirname "$target_dir")
          python translate.py "$file" "$target_dir" "ja"
        done
    - name: list files
      run: ls
      
    - name: Configure Git
      run: |
        git config user.name "Your Name"
        git config user.email "your.email@example.com"

    - name: Make changes and commit
      run: |
        git pull
        git add .
        git commit -m "Add Translate files to folder"
        git push
